trigger:
  none

stages:
  - stage: 'Test'
    displayName: 'Test'
    jobs:
      - job: 'TestJob'
        displayName: 'Test Job'
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - task: CmdLine@2
            displayName: Installs Cypress
            inputs:
              script: npm i
          - task: CmdLine@2
            displayName: Verifies Cypress
            inputs:
              script: npx cypress verify
          - task: CmdLine@2
            displayName: Displays Cypress Information
            inputs:
              script: npx cypress info
          - task: CmdLine@2
            displayName: 'Run Cypress tests'
            inputs:
              script: npx cypress run
            env:
              # avoid warnings about terminal
              TERM: xterm