trigger:
  none

stages:
  - stage: 'Test'
    displayName: 'Test'
    jobs:
      - job: 'TestJob'
        displayName: 'Test Job'
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - template: templates/pre-steps.yml
          - task: CmdLine@2
            displayName: 'Run Cypress tests'
            inputs:
              script: npx cypress run
            env:
              # avoid warnings about terminal
              TERM: xterm
          - template: templates/post-steps.yml